changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧹 Maintenance
      labels:
        - chore
        - refactor
        - docs
    - title: 🔒 Security
      labels:
        - security
    - title: Other Changes
      labels:
        - "*"