name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 mypy bandit pytest pytest-cov

      - name: Black
        run: black --check .
      - name: isort
        run: isort --check-only .
      - name: Flake8
        run: flake8 .
      - name: mypy
        run: mypy .
      - name: Bandit
        run: bandit -c .bandit -r .
      - name: Run tests with coverage
        run: pytest --maxfail=1 --disable-warnings -q \
             --cov=app --cov=gui --cov=db --cov=tools \
             --cov-report=xml --cov-fail-under=80
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: py${{ matrix.python-version }}
          fail_ci_if_error: true

  build:
    needs: lint-test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --name ARL-WiFi app/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ARL-WiFi-${{ matrix.os }}
          path: dist/ARL-WiFi*