name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 mypy bandit pytest pytest-cov

      - name: Black (format check)
        run: black --check .

      - name: isort (import order check)
        run: isort --check-only .

      - name: Flake8 (linting)
        run: flake8 .

      - name: mypy (type checking)
        run: mypy .

      - name: Bandit (security scan)
        run: bandit -c .bandit -r .

      - name: Run tests with coverage
        run: pytest --maxfail=1 --disable-warnings -q --cov=app --cov=gui --cov=db --cov=tools --cov-report=xml